// This file is auto-generated by ./bin/rails stimulus:manifest:update

import { application } from "controllers/application"

import GoogleSearchController from "controllers/google_search_controller"
application.register("google-search", GoogleSearchController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import ModalController from "controllers/modal_controller"
application.register("modal", ModalController)
