// This file is auto-generated by ./bin/rails stimulus:manifest:update

import { application } from "controllers/application"

import GoogleSearchController from "controllers/google_search_controller"
application.register("google-search", GoogleSearchController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import ModalController from "controllers/modal_controller"
application.register("modal", ModalController)

import NearbyFilterController from "controllers/nearby_filter_controller"
application.register("nearby-filter", NearbyFilterController)

import ImageLoadingController from "controllers/image_loading_controller"
application.register("image-loading", ImageLoadingController)
